# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-01 10:18
from __future__ import unicode_literals

import CoupleManager.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Male',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
                ('birthday', models.DateField()),
                ('height', models.IntegerField(validators=[django.core.validators.MinValueValidator(160), django.core.validators.MaxValueValidator(200)])),
                ('job', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=50, validators=[CoupleManager.models.lnglat_validator])),
                ('hobbys', models.CharField(max_length=200)),
                ('is_fulled', models.BooleanField()),
            ],
        ),
    ]
