# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-01 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoupleManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='male',
            name='hobbys',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='male',
            name='name',
            field=models.CharField(max_length=2),
        ),
    ]
