# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-01 10:38
from __future__ import unicode_literals

import CoupleManager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoupleManager', '0002_auto_20180401_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='male',
            name='job',
            field=models.CharField(max_length=10, validators=[CoupleManager.models.job_validator]),
        ),
        migrations.AlterField(
            model_name='male',
            name='name',
            field=models.CharField(max_length=5, validators=[CoupleManager.models.name_validator]),
        ),
    ]
