# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-01 11:14
from __future__ import unicode_literals

import CoupleManager.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoupleManager', '0003_auto_20180401_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Female',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, validators=[CoupleManager.models.name_validator])),
                ('birthday', models.DateField()),
                ('height', models.IntegerField(validators=[django.core.validators.MinValueValidator(150), django.core.validators.MaxValueValidator(190)])),
                ('job', models.CharField(max_length=10, validators=[CoupleManager.models.job_validator])),
                ('location', models.CharField(max_length=50, validators=[CoupleManager.models.lnglat_validator])),
                ('hobbys', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='male',
            name='hobbys',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
